-- File: dec224.vhd
-- Generated by MyHDL 0.8
-- Date: Tue Jun 18 00:21:15 2013


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_08.all;

entity dec224 is
    port (
        sel: in unsigned(1 downto 0);
        o: out unsigned(3 downto 0)
    );
end entity dec224;


architecture MyHDL of dec224 is






begin




DEC224_DECODER: process (sel) is
begin
    case sel is
        when "00" =>
            o <= to_unsigned(1, 4);
        when "01" =>
            o <= to_unsigned(2, 4);
        when "10" =>
            o <= to_unsigned(4, 4);
        when others => -- "11"
            o <= to_unsigned(8, 4);
    end case;
end process DEC224_DECODER;

end architecture MyHDL;
